export default function Head() {
  return (
    <>
      <title>Chat Room</title>
      <meta name="google-site-verification" content="dnW1TgJ5V2K2BLtrlGnYB9zT1glT6E43xb8aWiHuPzM" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
      crossOrigin="anonymous"
      referrerPolicy="no-referrer"
    />
    </>
  )
}
