import './globals.css'
import AuthContext from './AuthContext'
import Nav from './Nav'
import QueryWrapper from './QueryWrapper';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
      <AuthContext>
        <QueryWrapper>
           
      <Nav />
      {children}
      </QueryWrapper>
      </AuthContext>
      </body>
    </html>
  )
}
