import './globals.css'
import AuthContext from './AuthContext'
import Nav from './Nav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <AuthContext>
           {/* @ts-expect-error Server Component */}
      <Nav />
      {children}
      </AuthContext>
      </body>
    </html>
  )
}
